repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
-   repo: https://github.com/adambrenecki/pre-commit-python-sorter
    sha: 1.0.5
    hooks:
    -   id: python-import-sorter
